version: 2

sources:
  - name: erp 
    database: northwind-projeto-dw-391611
    schema: erp_northwind
    description: Fonte de dados de vendas do SAP northwind  
    tables:
      - name: employees
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null
      - name: products
        description: Tabela com os produtos comercializados pela Northwind
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
      - name: categories
        description: Tabela com as categorias dos produtos comercializados pela Northwind
        columns:
          - name: category_id
            tests:
              - unique
              - not_null

      - name: suppliers
        description: Fornecedores dos produtos comercializados pela Northwind
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null

      - name: orders
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados.
        columns:
          - name: order_id
            description: Chave primária da tabela de ordens.
            tests:
              - unique
              - not_null
            
      - name: order_details
        description: Detalhe de item linha para cada pedido da tabela.